#!/bin/bash

# Add all paths that will be needed. It does not matter if 
# for examlpe composer is not installed. It will be ready for 
# installation

# Add composer global packages 
# https://getcomposer.org/doc/03-cli.md#composer-home
export PATH="$PATH:$HOME/.config/composer/vendor/bin:$HOME/.composer/vendor/bin"


# Deno path
export DENO_INSTALL="/home/aleksandar2/.deno"
export PATH="$PATH:$DENO_INSTALL/bin"

# Flutter does not have predefined path, so I choose ~/.flutter
export PATH="$PATH:$HOME/.flutter/flutter/bin"

# Just use fixed path for node. NVM is to slow, and workaround 
# are prone to braking. Add nvm to path only when needed
export PATH="$PATH:$HOME/.nvm/versions/node/v12.16.1/bin"

# Yarn global modules path, must be after node
export PATH="$PATH:`yarn global bin`"

# Import all aliases
source ~/.config/aliases/standard

