#!/bin/sh

# Copy configs folder from ~/.dotfiles to ~
# --adopt is used to merge files in configs
# with already existing content
# stow configs --adopt -d ~/.dotfiles -t ~

# I switched to this frow stow, still little buggy
mackup restore
