#!/bin/bash
export DEBIAN_FRONTEND="noninteractive"

echo "Set root password"
sudo passwd root

echo "Add yarn repo"
# curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
# echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list

echo "Updating repositories"
sudo apt update -y & sudo apt upgrade -y

echo "Installing apt-transport-https"
sudo apt install -y apt-transport-https

echo "Installing zsh git vim curl wget xclip tmux"
sudo apt install -y zsh git vim curl wget xclip tmux

echo "Installing libssl-dev build-essential p7zip-full"
# sudo apt install -y libssl-dev build-essential p7zip-full

echo "Installing Android drivers"
# sudo apt install -y android-tools-adb

echo "Install Fira Code, Roboto, Font Awesome "
# sudo apt install -y fonts-firacode fonts-roboto fonts-font-awesome

# echo "Install Stow"
# sudo apt install -y stow
# Install pip and Mackup
sudo apt install -y python3-pip
pip3 install mackup

echo "Install neovim"
sudo apt install -y neovim

echo "Install vim-plug for neovim"
sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
       https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'

# Install vim plugins
nvim +PlugInstall +qall

echo "Install node"
# It's a lot faster loading time to use this node instead of nvm
# Ubuntu built in node uses version 10, which is old.
# curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
# sudo apt-get install -y nodejs
curl -fsSL https://fnm.vercel.app/install | bash
source /home/aleksandar/.bashrc
fnm install --lts


echo "Installing Docker"
# Install docker from ubuntu repositories
sudo apt install -y docker.io docker-compose

# echo "Installing PHP"
# sudo apt install -y php

echo "Installing sqlite3"
sudo apt install -y sqlite3

# echo "Installing composer"
# sudo apt install -y composer

# echo "Installing common PHP packages"
# sudo apt install -y php-xml php-mbstring php-zip
# sudo apt install -y libapache2-mod-php php-mysql

# echo "Installing yarn"
# sudo apt install --no-install-recommends yarn

echo "Some needed node modules"
# yarn global add diff-so-fancy typescript typeorm
npm install -g diff-so-fancy typescript tldr

# Install zim (framework for zsh)
curl -fsSL https://raw.githubusercontent.com/zimfw/install/master/install.zsh | zsh
