- hosts: localhost
  # I'm testing in ubuntu docker, so it fails because flatpak and vscode
  # are not configured in ubuntu
  ignore_errors: yes
  pre_tasks:
    - name: Update apt
      become: true
      apt:
        update_cache: true
        upgrade: dist
  tasks:
    # Install required apt packages
    - include: ansible/tasks/apt.yml
    # Clone this repo and copy dotfiles
    - include: ansible/tasks/dotfiles.yml
    # Decrypt it's secrets
    - include: ansible/tasks/decrypt.yml
    # Install nix and home-manager packages
    - include: ansible/tasks/nix.yml
    # Disable root
    - include: ansible/tasks/disable_root.yml
    # Configure zsh
    - include: ansible/tasks/zsh.yml
    # Install NodeJS
    - include: ansible/tasks/node.yml
    - include: ansible/tasks/gui.yml
    - include: ansible/tasks/replace_debs.yml
    - include: ansible/tasks/dev.yml
    - include: ansible/tasks/gaming.yml
    - include: ansible/tasks/dconf.yml
    - include: ansible/tasks/neovim.yml
    - include: ansible/tasks/mount.yml
    - include: ansible/tasks/nerd_fonts.yml
    - include: ansible/tasks/regular_fonts.yml
    - include: ansible/tasks/home_links.yml
    - include: ansible/tasks/docker.yml
    - include: ansible/tasks/flutter.yml
    - include: ansible/tasks/backup.yml
