#!/bin/bash

export DEBIAN_FRONTEND="noninteractive"

echo "Set root password"
sudo passwd root

echo "Updating repositories"
sudo apt update -y & sudo apt upgrade -y

echo "Installing apt-transport-https"
sudo apt install -y apt-transport-https

echo "Installing zsh git vim curl wget xclip tmux htop"
sudo apt install -y zsh git vim curl wget xclip tmux htop

echo "Installing libssl-dev build-essential p7zip-full"
sudo apt install -y libssl-dev build-essential p7zip-full

echo "Installing Android drivers"
sudo apt-get install android-tools-adb android-tools-fastboot

echo "Installing sqlite3"
sudo apt install -y sqlite3

echo "Install pip"
sudo apt install -y python3-pip

echo "Install Mackup"
pip3 install --upgrade mackup

# Clone dotfiles
git clone https://github.com/apstanisic/dotfiles.git ~/dotfiles
# Make paths and aliases available in shell
source ~/dotfiles/Mackup/.config/paths
source ~/dotfiles/Mackup/.config/aliases
# Initialize Mackup
cp ~/dotfiles/Mackup/.mackup.cfg ~/.mackup.cfg
# Restore config
mackup restore -f


echo "Install neovim"
sudo apt install -y neovim

echo "Install vim-plug for neovim"
sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
		       https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'

# Install vim plugins
nvim +PlugInstall +qall

echo "Install node"
# Install volta (Node installer)
curl https://get.volta.sh | bash
# Install Node
volta install node@lts
# Prettier git diff
volta install diff-so-fancy
# Global Typescript
volta install typescript
# Cheatsheet
volta install tldr
# Nest CLI
volta install @nestjs/cli

echo "Installing Docker"
# Install docker from ubuntu repositories
sudo apt install -y docker.io docker-compose

# Set zsh as default shell
sudo chsh -s /usr/bin/zsh aleksandar

# Shell alias
install-starship

# Install zim (framework for zsh)
curl https://github.com/zimfw/zimfw/releases/latest/download/zimfw.zsh --create-dirs -o ~/.zim/zimfw.zsh -L
zsh ~/.zim/zimfw.zsh install
#curl -fsSL https://raw.githubusercontent.com/zimfw/install/master/install.zsh | zsh
