#!/bin/bash

# export NVM_DIR="$HOME/.nvm"
# [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
# [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

export PATH="$PATH:$HOME/.nvm/versions/node/v12.6.0/bin"
# Add composer global packages
export PATH="$PATH:$HOME/.composer/vendor/bin"
# Add deno executable if installed
export PATH="$PATH:$HOME/.deno/bin"
export PATH="$PATH:$HOME/.local/share/flutter/bin"

# Import all aliases
source ~/.config/aliases/combined
