#!/bin/bash
export DEBIAN_FRONTEND="noninteractive"
# source ./paths.sh

echo "Set root password"
sudo passwd root

echo "Add yarn repo"
curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list

echo "Updating repositories"
sudo apt update -y & sudo apt upgrade -y

echo "Installing zsh git vim curl wget xclip tmux"
sudo apt install -y zsh git vim curl wget xclip tmux

echo "Installing libssl-dev build-essential p7zip-full"
sudo apt install -y libssl-dev build-essential p7zip-full

echo "Installing Android drivers"
sudo apt install -y android-tools-adb

echo "Install Fira Code"
sudo apt install -y fonts-firacode

echo "Install Stow"
sudo apt install -y stow

echo "Install neovim"
sudo apt install -y neovim

echo "Install vim-plug for neovim"
curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

echo "Installing nvm"
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

echo "Installing node"
nvm install node

echo "Installing Docker"
sudo apt-get remove docker docker-engine docker.io containerd runc
sh -c "$(curl -fsSL get.docker.com)"

echo "Install docker compose"
sudo curl -L "https://github.com/docker/compose/releases/download/1.24.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
sudo chmod +x /usr/local/bin/docker-compose


echo "Installing PHP"
sudo apt install -y php

echo "Installing sqlite3"
sudo apt install -y sqlite3

echo "Installing composer"
sudo apt install -y composer

echo "Installing PHP packages"
sudo apt install -y php-mcrypt php-xml php-mbstring php-zip
sudo apt install -y libapache2-mod-php php-mysql

echo "Installing yarn"
sudo apt install --no-install-recommends yarn

echo "Cloning config repo"
git clone https://github.com/apstanisic/dotfiles.git .dotfiles

