#!/bin/bash

# Open neovim
alias v='nvim'

# Exit terminal
alias e='exit'

# Clear screen
alias c='clear'

# Go to home folder and clear screen
alias cdc='cd ~ && clear'

# Show hidden files
alias la='ls -A'

# Better "ls"
# Short 
alias xs='exa --icons --group-directories-first'
# Short with hidden
alias xa='xs -a'
# Long without hidden
alias x='xs -l'
# Long with hidden
alias xx='xs -al'
# tree
alias tree='xs --tree'


# Put files in trash instead of removing them
alias tr='trash-put'

# Copy recursively by default
alias cp='cp -R'
# Better copy with progress bar, so I know operation is not stuck
# alias rs='rsync -a --info=progress2 -h --no-i-r'


# Docker Compose
alias dcu='docker-compose up'
alias dcd='docker-compose down'

# npm
alias nrd='npm run dev'

# Kill program
alias kl='killall -9'

# apt
alias sa='sudo apt'
alias ai='sudo apt install'

# Update all packages
alias update='topgrade'
alias u='update'

# Check weather in terminal for current IP
alias wt='curl wttr.in'

# Attach to tmux session
alias ta='tmux attach -t'

# Rerun previous command with sudo
alias again='sudo $(fc -ln -1)'

# Git aliases
alias ga='git add'
alias gaa='git add --all'
alias gac='git add --all && git commit'
alias gc='git commit'
alias gd='git diff'
alias gp='git push'
# gs is already used in Ubuntu for ghostscript
alias gs='git status'
alias gst='git status'

# Open file with gui app
alias open='xdg-open'

# Alias to go up the path
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'
alias ......='cd ../../../../..'
alias .......='cd ../../../../../..'
alias ........='cd ../../../../../../..'
alias .........='cd ../../../../../../../..'
alias ..........='cd ../../../../../../../../..'


# Copy file to clipboard. Does not work in wayland
# cb file.txt
# alias cb='xclip -sel c < '


# Maybe use Nix
# Or fvm
# Install flutter with all dependecies for Linux desktop development
install_flutter()
{
    git clone https://github.com/flutter/flutter.git -b stable --depth 1 ~/.local/share/flutter-sdk
    sudo apt install clang cmake ninja-build pkg-config libgtk-3-dev
    flutter precache
    flutter config --enable-linux-desktop
}

