#!/bin/bash

# Add all paths that will be needed. It does not matter if
# for examlpe composer is not installed. It will be ready for
# installation

# https://linuxize.com/post/bash-check-if-file-exists/
# "-e" check if there is any file, "-f" checks for regular file (not folder) 

# Initialize node/fnm/npm/pnpm if installed
if [ -e "$HOME/.fnm" ]; then
    export PATH="$PATH:$HOME/.fnm"
    eval "$(fnm env)"  
fi

# Initialize cargo/rust if installed
if [ -e "$HOME/.cargo/env" ]; then
    source $HOME/.cargo/env
fi
