only = [
  "system",
  "flatpak",
  "nix",
  "deno",
  "node",
  "custom_commands",
  "tldr",
  "gnome_shell_extensions",
  "cargo",
  "rustup",
  "composer"
]


# Do not stop execution and ask me to retry
no_retry = true

# Don't ask for confirmation
assume_yes = true

# Remove temporary files
cleanup = true

# Update composer if installed and outdated
[composer]
self_update = true

# npm should never use sudo 
# It should be installed with fnm, which does not require sudo
[npm]
use_sudo = false

# Custom commands
[commands]
# topgrade runs this command with "zsh -c" which does not source
# .zshrc, where zim puts it's function, so we source zimfw manually
"Zim" = "source $HOME/.zim/init.zsh && zimfw upgrade && zimfw update"

