---
# Maybe mount by label
- name: Mount drive
  tags:
    - mount_uuid
  block:
    - name: Get stats for drive
      stat:
        path: /dev/sda1
      register: sda
    - name: Create mount folder if it does not exist 
      file:
        path: /media/hdd500
        state: directory
        mode: '0755'

    - name: Get drive UUID
      when: sda.stat.exists and sda.stat.isblk
      shell: blkid -o value -s UUID /dev/sda1
      # Remember to call drive_uuid.stdout
      register: drive_uuid

    - name: Register drive
      become: true
      when: sda.stat.exists and sda.stat.isblk and 1 == 2
      mount:
        # Steam uses `/media`, so will I, less chance to cause problem with games
        path: /media/hdd500
        # I have 1 hdd and 1 nvme, so hdd will always be sda1
        src: UUID={{ drive_uuid.stdout }}
        # It's ext4, in future maybe switch to btrfs
        fstype: ext4
        # Also possible
        # fstype: auto
        # Should be mounted
        state: present
        # nofail - It will boot normally even if drive fails
        # x-gvfs-show - Tell gnome to show in Files
        # x-gvfs-name - Tell gnome what name to use
        opts: x-gvfs-show,nofail,x-gvfs-name=HardDrive500
