- name: apt
  block:
    - name: Install packages
      become: true
      apt:
        pkg:
          - curl
          - wget
          - apt-transport-https
          - git
          - libssl-dev
          - build-essential
          - zip
          - p7zip-full
          - android-tools-adb
          - android-tools-fastboot
            # installed in dotfiles.yml
            #          - stow
