- name: apt
  tags:
    - apt
  block:
    - name: Install common packages
      become: true
      apt:
        pkg:
          - curl
          - wget
          - apt-transport-https
          - git
          - libssl-dev
          - build-essential
          - android-tools-adb
          - android-tools-fastboot
          - android-sdk-platform-tools
          - zip
          - unrar
          - p7zip-full
