- name: Ensure curl
  become: true
  apt:
    name: curl
  tags:
    - brave
- name: Add brave keyring
  become: true
  shell: |
    curl -fsSLo /usr/share/keyrings/brave-browser-archive-keyring.gpg https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg
  tags:
    - brave
- name: Add PPA
  become: true
  shell: |
    echo "deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg arch=amd64] https://brave-browser-apt-release.s3.brave.com/ stable main"| tee /etc/apt/sources.list.d/brave-browser-release.list
  tags:
    - brave
- name: Install brave
  become: true
  ansible.builtin.apt:
    update_cache: yes
    name: brave-browser
  tags:
    - brave
