--- 
- name: Docker
  tags:
    - docker
    - dev
  block:
    - name: Install docker
      become: true
      apt: 
        name: docker.io

    - name: Install docker-compose
      become: true
      apt: 
        name: docker-compose

    # Need for running docker without sudo
    # https://docs.docker.com/engine/install/linux-postinstall/
    - name: Create docker group
      become: true
      group:
        name: docker
        state: present

    - name: Add user to docker group 
      become: true
      user:
        name: aleksandar
        groups: docker
        append: true


