- name: Dotfiles
  tags:
    - dotfiles
  block:
    # TODO Download chezmoi only if there is no local version available
    - name: Install chezmoi
      shell: sh -c "$(curl -fsLS get.chezmoi.io)" -- -b $HOME/.local/bin

    - name: Install deps
      become: true
      apt:
        pkg:
          - git
    - name: Check if ~/.dotfiles exists
      stat:
        path: $HOME/.dotfiles
      register: is_cloned

    - name: Check if ssh exists
      stat:
        path: $HOME/.ssh
      register: ssh_exists

      # Ignore error if ssh does not have access
      # Since it will fallback to http version
    - name: Clone dotfiles repo with ssh if possible
      ignore_errors: yes
      git:
        repo: "git@github.com:apstanisic/dotfiles.git"
        dest: $HOME/.dotfiles
        version: main
      when: not is_cloned.stat.exists and ssh_exists.stat.exists

    - name: Clone dotfiles repo without ssh if needed
      git:
        repo: "https://github.com/apstanisic/dotfiles.git"
        dest: $HOME/.dotfiles
        version: main
      when: not is_cloned.stat.exists

    - name: Sync dotfiles
      shell: $HOME/.local/bin/chezmoi apply --force

      # Nix will install it later with home-manager
    - name: Remove local chezmoi
      file:
        path: $HOME/.local/bin/chezmoi
        state: absent
