- name: Dotfiles
  tags:
    - dotfiles
  block:
    - name: Clone dotfiles repo
      git:
        repo: "https://github.com/apstanisic/dotfiles.git"
        dest: $HOME/.dotfiles
        version: main

    # -b is for binary location. We will install it properly later with nix,
    # so we are simply putting it in /tmp.
    # We already cloned our dotfiles, so we only need to provide source
    - name: Setup dotfiles
      shell: sh -c "$(curl -fsLS get.chezmoi.io)" -- -b /tmp init --apply --source=~/dotfiles/dotfiles

