- name: Flutter
  tags:
    - flutter
    - never
  block:
    - name: Clone flutter repo
      git:
        repo: "https://github.com/flutter/flutter.git"
        dest: $HOME/.local/share/flutter-git
        version: stable
        depth: 1
