- name: Gaming
  tags:
    - home
    - gaming
  block:
    - name: Install gamepad support for Steam Flatpak
      become: true
      apt:
        name: steam-devices

    - name: Install Bottles
      flatpak:
        name: com.usebottles.bottles
        method: user

    - name: Install Steam
      flatpak:
        name: com.valvesoftware.Steam
        method: user

    # - name: Install AntiMicroX
    #   flatpak:
    #     name: io.github.antimicrox.antimicrox
    #     method: user
# # Maybe I do not need Lutris and ProtonUp, because of bottles
#    - name: Install Lutris
#      flatpak:
#        name: net.lutris.Lutris
#        method: user

#    - name: Install ProtonUp
#      flatpak:
#        name: net.davidotek.pupgui2
#        method: user

