- name: GUI apps
  tags:
    - gui
  # Only browser, terminal and IDE are apts
  block:
    - name: Install fonts
      become: true
      apt:
        pkg:
          - fonts-firacode
          - fonts-roboto
          - fonts-font-awesome
    - name: Remove LibreOffice deb
      become: true
      apt:
        name: libreoffice*
        state: absent
    - name: Install tilix
      become: true
      apt:
        name: tilix
    - name: Install vscode
      # Switch to either Flatpak or nix, since pop-os version is lagging behind
      # Not available in ubuntu, only in pop-os
      ignore_errors: yes
      become: true
      apt:
        name: code
    - name: Install common Flatpak apps
      # Not available in ubuntu, only in pop-os
      ignore_errors: yes
      community.general.flatpak:
        name:
            # Testing using brave as flatpak 
          - com.brave.Browser
          - com.spotify.Client
          - com.stremio.Stremio
          - io.dbeaver.DBeaverCommunity
          - com.transmissionbt.Transmission
          - com.calibre_ebook.calibre
          - org.libreoffice.LibreOffice
          - io.github.celluloid_player.Celluloid
          - com.github.tchx84.Flatseal
          - com.mattjakeman.ExtensionManager
            # Shell integration does not work in flatpak 
            # - org.wezfurlong.wezterm
