---
- name: Mount internal hard drive
  tags:
    - mount
    - home
  block:
    - name: Unlock LUKS
      become: true
      community.crypto.luks_device:
        uuid: af27ae1d-5df4-4d86-864b-717e3987bd31
        keyfile: "{{ ansible_env.HOME }}/.config/hdd500-secret-key.txt"
        state: opened
        name: hdd-drive

    - name: Unlock LUKS on startup
      become: true
      no_log: true
      community.general.crypttab:
        backing_device: UUID=af27ae1d-5df4-4d86-864b-717e3987bd31
        password: "{{ ansible_env.HOME }}/.config/hdd500-secret-key.txt"
        name: /dev/mapper/hdd-drive
        state: present
        opts: luks

    - name: Create mount folder if it does not exist
      become: true
      file:
        path: /media/hdd500
        state: directory
        owner: aleksandar
        group: aleksandar
        mode: "0777"


    - name: Mount drive on startup
      become: true
      mount:
        # Steam uses `/media`, so will I, less chance to cause problem with games
        path: /media/hdd500
        # src: LABEL=HARD_DRIVE_001
        # This is path of mapped LUKS drive
        src: /dev/mapper/hdd-drive
        # It's ext4, in future maybe switch to btrfs
        fstype: ext4
        # Also possible
        # fstype: auto
        # Should be mounted
        # state: present
        state: mounted
        # nofail - It will boot normally even if drive fails
        # x-gvfs-show - Tell gnome to show in Files
        # x-gvfs-name - Tell gnome what name to use
        opts: x-gvfs-show,nofail,x-gvfs-name=HardDrive500
