---
# This is better than uuid since hard drive label
# will be same after reinstalling os,
# and there is no danger that some other device
# might be at /dev/sda1
- name: Mount drive
  tags:
    - mount
  block:
    - name: Create mount folder if it does not exist
      become: true
      file:
        path: /media/hdd500
        state: directory
        owner: aleksandar
        group: aleksandar
        mode: '0755'

    - name: Check if drive exists
      # command return path to drive (/dev/sda1), or fails
      # so we can simply echo false if command fails 
      # and later check if return value is false (drive_exists.stdout)
      shell: blkid --label HARD_DRIVE_001 || echo false
      register: drive_exists

    - name: Register drive by label
      become: true
      when: drive_exists.stdout != "false"
      mount:
        # Steam uses `/media`, so will I, less chance to cause problem with games
        path: /media/hdd500
        # I have 1 hdd and 1 nvme, so hdd will always be sda1
        src: LABEL=HARD_DRIVE_001
        # It's ext4, in future maybe switch to btrfs
        fstype: ext4
        # Also possible
        # fstype: auto
        # Should be mounted
        state: present
        # nofail - It will boot normally even if drive fails
        # x-gvfs-show - Tell gnome to show in Files
        # x-gvfs-name - Tell gnome what name to use
        opts: x-gvfs-show,nofail,x-gvfs-name=HardDrive500


