---
# Mount hdd
# https://github.com/ValveSoftware/Proton/wiki/Using-a-NTFS-disk-with-Linux-and-Windows
- name: Mount drive
  tags:
    - mount
  block:
    - name: Get stats for drive
      stat:
        path: /dev/sda1
      register: sda

    - name: Get drive UUID
      when: sda.stat.exists and sda.stat.isblk
      shell: blkid -o value -s UUID /dev/sda1
      # Remember to call drive_uuid.stdout
      register: drive_uuid

    - name: Register drive
      become: true
      when: sda.stat.exists and sda.stat.isblk
      mount:
        # Steam uses `/media`, so will I, less chance to cause problem with games
        path: /media/hdd500
        # I have 1 hdd and 1 nvme, so hdd will always be sda1
        src: UUID={{ drive_uuid.stdout }}
        # It's ext4, in future maybe switch to btrfs
        fstype: auto
        # fstype: ext4
        # Should be mounted
        state: present
        opts: x-gvfs-show,nofail,x-gvfs-name=HardDrive500
        # 
        # steam example:
        # UUID=38CE9483CE943AD8 /media/gamedisk ntfs uid=1000,gid=1000,rw,user,exec,umask=000 0 0
        # uid - User's id this device belongs to
        # gid - User's group id this device belongs to
        # rw - It s read and write, ro means it's read only
        # user - User is allowed to mount this device
        # exec  - Files on this device can be executed
        # umask - I think is like permission, only reversed, 000 is rwx
        # nofail - It will boot normally even if drive fails
        # x-gvfs-show - Tell gnome to show in Files
        # x-gvfs-name - Tell gnome what name to use
        # opts: uid=1000,gid=1000,rw,user,exec,umask=000,x-gvfs-show,nofail,x-gvfs-name=HardDrive500
