- name: Neovim
  tags: 
    - neovim
  environment:
    PATH: "{{ ansible_env.PATH }}:{{ ansible_env.HOME }}/.nix-profile/bin"
  block:
    # Neovim should be installed with nix
    - name: Install AstroNvim
      git:
        repo: 'https://github.com/AstroNvim/AstroNvim'
        dest: '{{ ansible_env.HOME }}/.config/nvim'
        depth: 1

    - name: Init AstroNvim
      shell: nvim --headless +q
