- name: Neovim
  tags: 
    - neovim
  block:
    - name: Install neovim
      become: true
      apt:
        # Neovim should be installed with nix
        pkg: 
          - neovim
          - git 
          - curl
    - name: Install packer
      git:
        repo: 'https://github.com/wbthomason/packer.nvim'
        dest: '{{ ansible_env.HOME }}/.local/share/nvim/site/pack/packer/start/packer.nvim'
        depth: 1
    - name: Check if neovim config exists
      stat:
        path: $HOME/.config/nvim/init.lua
      register: config_exists

    - name: Install neovim packages
      shell: nvim --headless -c 'autocmd User PackerComplete quitall' -c 'PackerSync'
      when: config_exists.stat.exists

