- name: Neovim
  tags: 
    - neovim
  block:
    # - name: Install neovim
    #   become: true
    #   apt:
    #     # Neovim should be installed with nix
    #     pkg: 
    #       - neovim
    #       - git 
    #       - curl
    - name: Install AstroNvim
      git:
        repo: 'https://github.com/AstroNvim/AstroNvim'
        dest: '{{ ansible_env.HOME }}/.config/nvim'
        depth: 1

#    - name: Init AstroNvim
#      shell: nvim --headless -c 'autocmd User LazyDone quitall'
