- name: Install Nix
  environment:
    NIX_PATH: "{{ ansible_env.HOME }}/.nix-defexpr/channels:/nix/var/nix/profiles/per-user/root/channels${NIX_PATH:+:$NIX_PATH}"
  tags:
    - nix
  block:
  - name: Install nix
    shell: curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix/tag/v0.9.0 | sh -s -- install --no-confirm
    become: true

  - name: Add Home Manager
    args:
      executable: /bin/bash
    shell: |
      # Default nix installer add path to this
      source $HOME/.profile;
      # nix-installer adds path here
      source /etc/bashrc;
      nix-channel --add https://github.com/nix-community/home-manager/archive/master.tar.gz home-manager;
      nix-channel --update;
      nix-shell '<home-manager>' -A install
      home-manager switch
