- name: Nix packages
  tags:
    - nix_pkg
  vars:
    set_src: "if [ -e $HOME/.nix-profile/etc/profile.d/nix.sh ]; then . $HOME/.nix-profile/etc/profile.d/nix.sh; fi;"
    inst: "nix-env -iA nixpkgs"
    nix_inst: "{{ set_src }} {{ inst }}"
  block:
    - name: Install starship
      shell: "{{ nix_inst }}.starship"
    - name: Install bat
      shell: "{{ nix_inst }}.bat"
    - name: Install exa
      shell: "{{ nix_inst }}.exa"
    - name: Install ripgrep
      shell: "{{ nix_inst }}.ripgrep"
    # Fuzzy finder
    - name: Install fzf
      shell: "{{ nix_inst }}.fzf"
    # better git diff
    - name: Install delta
      shell: "{{ nix_inst }}.delta"
    # better find
    - name: Install fd
      shell: "{{ nix_inst }}.fd"
    # Neovim
    - name: Install neovim
      shell: "{{ nix_inst }}.neovim"
    # see what files takes space (Better ncdu)
    - name: Install gdu
      shell: "{{ nix_inst }}.gdu"
    # Htop
    - name: Install htop
      shell: "{{ nix_inst }}.htop"
    # multiplexer
    - name: Install tmux
      shell: "{{ nix_inst }}.tmux"
    # Better cp
    - name: Install rsync
      shell: "{{ nix_inst }}.rsync"
    # Sync and encrypt with cloud providers
    - name: Install rclone
      shell: "{{ nix_inst }}.rclone"
    # rm with support for trash
    - name: Install trash
      shell: "{{ nix_inst }}.trash-cli"
    # update all packages
    - name: Install topgrade
      shell: "{{ nix_inst }}.topgrade"
    # Cheatsheet (c version)
    - name: Install tldr
      shell: "{{ nix_inst }}.tldr"
    # Better ctrl+r
    - name: Install mcfly
      shell: "{{ nix_inst }}.mcfly"
    # httpie in rust, similar as curl
    - name: Install xh
      shell: "{{ nix_inst }}.xh"
    # better df
    - name: Install duf
      shell: "{{ nix_inst }}.duf"
    # better tmux
    - name: Install zellij
      shell: "{{ nix_inst }}.zellij"
    # jumper
    - name: Install zoxide
      shell: "{{ nix_inst }}.zoxide"
      # Dev
    - name: deno
      shell: "{{ nix_inst }}.deno"
    # docker compose
    - name: docker-compose
      shell: "{{ nix_inst }}.docker-compose"
    #g shellc "{{ nix_inst}}.li"
    - name: gh
      shell: "{{ nix_inst }}.gh"
    # Sqlite
    - name: sqlite
      shell: "{{ nix_inst }}.sqlite"
