---
# FNM is installed with nix/home-manager
- name: Node
  environment:
    PATH: "{{ ansible_env.PATH }}:{{ ansible_env.HOME }}/.nix-profile/bin"
  tags:
    - node
  block:
    - name: Install NodeJS
      shell: fnm install --lts

    # We do not have access to npm at this point, so we have to use fnm
    # TODO See if we can use `fnm env` to set paths in ansible
    - name: Install yarn
      shell: fnm exec --using=default npm install -g yarn

    - name: Install pnpm
      shell: fnm exec --using=default npm install -g pnpm

    - name: Install pnpm
      shell: fnm exec --using=default npm install -g typescript

    - name: Install npm-check-updates
      shell: fnm exec --using=default npm install -g npm-check-updates
