---
# FNM is installed with nix/home-manager
- name: Node
  tags:
    - node
  block:
    - name: Install NodeJS
      shell: fnm install --lts

    - name: Install yarn
      npm:
        name: yarn
        global: true

    - name: Install pnpm
      npm:
        name: pnpm
        global: true

    - name: Install typescript
      npm:
        name: typescript
        global: true

    - name: Install npm-check-updates
      npm:
        name: npm-check-updates
        global: true
