- name: Node
  tags:
    - node
  environment:
    PATH: "{{ ansible_env.PATH }}:{{ ansible_env.HOME }}/.fnm"
  block:
    - name: Ensure dependencies
      become: true
      apt:
        pkg:
          - curl
          - unzip
    - name: Install FNM
      shell: curl -fsSL https://fnm.vercel.app/install | bash -s -- --skip-shell
    - name: Install NodeJS
      shell:
        cmd: |
          eval "$(fnm env)"
          fnm install --lts
    - name: Install pnpm
      shell:
        cmd: |
          eval "$(fnm env)"
          npm install -g pnpm
