- name: Install regular fonts
  tags:
    - regular_fonts
  block:
    - name: Ensure deps     
      become: true    
      apt: name=git    
     
    - name: Check if repo is already cloned    
      stat:    
        path: /tmp/nerd-fonts    
      register: is_cloned    
     
    - name: Clone nerd fonts    
      when: not is_cloned.stat.exists    
      shell: git clone --depth 1 --filter=blob:none --sparse https://github.com/ryanoasis/nerd-fonts.git /tmp/nerd-fonts    

    - name: Ensure script is runnable
      file:
        path: ./copy_normal_fonts.bash
        mode: u+x

      # relative to local.yml
    - name: Install SourceCodePro
      shell: ./copy_normal_fonts.bash SourceCodePro
     
    - name: Install JetBrainsMono
      shell: ./copy_normal_fonts.bash JetBrainsMono

    - name: Install CascadiaCode
      shell: ./copy_normal_fonts.bash CascadiaCode

    - name: Clear font cache
      become: true
      shell: fc-cache -fv

