- name: Replace .deb apps with flatpak
  tags:
    - replace_debs
  # Only browser, terminal and IDE are apts
  block:
    - name: Remove debs
      become: true
      apt:
        purge: true
        state: absent
        pkg:
          # Calendar
          - gnome-calendar
          # Contacts
          - gnome-contacts
          # Calculator
          - gnome-calculator
          # Weather
          - gnome-weather
          # Text editor
          - gedit
            # video player
          - totem
            # document viewer
          - evince
            # disk usage
          - baobab
            # image viewer
          - eog
            # document scanner
          - simple-scan
            # email
          - geary
            # extensions app (using extensions manager)
          - gnome-shell-extension-prefs

    - name: Remove LibreOffice deb
      become: true
      apt:
        name: libreoffice*
        state: absent

    - name: Install LibreOffice 
      flatpak:
        method: user
        name: org.libreoffice.LibreOffice

    - name: Install Calculator
      flatpak:
        method: user
        name: org.gnome.Calculator

    - name: Install Calendar
      flatpak:
        method: user
        name: org.gnome.Calendar

    - name: Install Text editor
      flatpak:
        method: user
        name: org.gnome.TextEditor

    - name: Install document viewer
      flatpak:
        method: user
        name: org.gnome.Evince

    - name: Install image viewer
      flatpak:
        method: user
        name: org.gnome.Loupe
