- name: ZSH
  tags:
    - zsh
  block:
    - name: Install zsh
      become: true
      apt:
        pkg:
          - zsh

    - name: Change shell
      become: true
      user:
        name: aleksandar
        shell: /usr/bin/zsh
        state: present
      # Old method
      # shell: usermod -s `which zsh` aleksandar

    - name: Install plugin manager
      git:
        repo: 'https://github.com/marlonrichert/zsh-snap.git'
        dest: "{{ ansible_env.HOME }}/.znap/zsh-snap" 
        depth: 1

    - name: Install plugins
      shell: zsh $HOME/.dotfiles/scripts/update_zsh_plugins.zsh 

    # This is because some programs (for example zimfw) modify .zshrc, and .zshenv. This way
    # nobody will change my config
    # This injects config, only if file exists
    - name: Link zshrc config
      shell: grep -qF 'if [ -e $HOME/.config/zsh/zshrc ]; then . $HOME/.config/zsh/zshrc; fi' ~/.zshrc || echo 'if [ -e $HOME/.config/zsh/zshrc ]; then . $HOME/.config/zsh/zshrc; fi' >> ~/.zshrc

    - name: Link zshenv config
      shell: grep -qF 'if [ -e $HOME/.config/zsh/zshenv ]; then . $HOME/.config/zsh/zshenv; fi' ~/.zshenv || echo 'if [ -e $HOME/.config/zsh/zshenv ]; then . $HOME/.config/zsh/zshenv; fi' >> ~/.zshenv
