#!/bin/bash

# Open neovim
alias v='nvim'
alias vi='nvim'
alias vim='nvim'

# Exit terminal
alias e='exit'
alias q='exit'

# Clear screen
alias c='clear'

# Go to home folder and clear screen
alias cdc='cd ~ && clear'

# Show hidden files
alias la='ls -A'

# Better "ls"
# Short 
alias xs='exa --icons --group-directories-first'
# Short with hidden
alias xa='xs -a'
# Long without hidden
alias x='xs -l'
# Long with hidden
alias xx='xs -al'
# tree
alias tree='xs --tree'


# Put files in trash instead of removing them
# I have to leave rm and rmdir because of scripts, but print warning 
alias tr='trash put'
alias rm='echo "Use tr, it is safer cause it puts files in trash" && \rm'
alias rmdir='echo "Use tr, it is safer cause it puts files in trash" && \rmdir'

# Copy recursively by default
alias cp='cp -R'
# Better copy with progress bar, so I know operation is not stuck
# alias rs='rsync -a --info=progress2 -h --no-i-r'


# Docker Compose
alias dcu='docker-compose up'
alias dcd='docker-compose down'

# npm
alias nrd='npm run dev'
alias nrdt='npm run dev:tmux'
alias nrb='npm run build'
alias nrs='npm run start'

# Kill program
alias kl='killall -9'

# apt
alias sa='sudo apt'
alias ai='sudo apt install'

# Update all packages
alias update='topgrade'
alias u='update'

# Check weather in terminal for current IP
alias wt='curl wttr.in'

# Attach to tmux session
alias ta='tmux attach -t'
alias tks='tmux kill-server'

# Simpler tmux
alias zj='zellij'

# Switch from Docker to Podman
alias docker='podman'

# Rerun previous command with sudo
alias again='sudo $(fc -ln -1)'

# Git aliases
alias ga='git add'
alias gaa='git add --all'
alias gac='git add --all && git commit'
alias gc='git commit'
alias gd='git diff'
alias gp='git push'
# gs is already used in Ubuntu for ghostscript
alias gs='git status'
alias gst='git status'

# Open file with gui app
alias open='xdg-open'

# Alias to go up the path
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'
alias ......='cd ../../../../..'
alias .......='cd ../../../../../..'
alias ........='cd ../../../../../../..'
alias .........='cd ../../../../../../../..'
alias ..........='cd ../../../../../../../../..'

# alias cloud-sync="rclone sync --progress /home/aleksandar/HDD/Media KoofrEncrpypted:"
alias cloud-sync="bash ~/.dotfiles/scripts/rclone-backup.sh"

# Copy file to clipboard. Does not work in wayland
# cb file.txt
# alias cb='xclip -sel c < '
alias cb-copy='wl-copy'
alias cb-paste='wl-paste'
alias cbc='wl-copy'
alias cbp='wl-paste'

# Run command multiple times
# Weird () is creating inner shell so i can call `set -e` without affecting global
# many() {(
#     set -e
#     number=$1
#     shift
#     for i in `seq $number`; do
#       echo Loop $i
#       $@
#     done
# )}
