#!/bin/bash

# Add all paths that will be needed. It does not matter if
# for examlpe composer is not installed. It will be ready for
# installation

# https://linuxize.com/post/bash-check-if-file-exists/
# "-e" check if there is any file, "-f" checks for regular file (not folder) 
# Maybe do this, add to path only if there is not currently
#  if ! [[ "$PATH" =~ "$HOME/.local/bin:" ]]

# Initialize fnm if installed
if [ -e "$HOME/.fnm" ]; then
    export PATH="$PATH:$HOME/.fnm"
    eval "$(fnm env)"  
fi

# Initialize cargo/rust if installed
if [ -e "$HOME/.cargo/env" ]; then
    source $HOME/.cargo/env
fi

# Initialize Home Manager if installed
if [ -e "$HOME/.nix-profile/etc/profile.d/hm-session-vars.sh" ]; then
	export NIX_PATH=$HOME/.nix-defexpr/channels:/nix/var/nix/profiles/per-user/root/channels${NIX_PATH:+:$NIX_PATH}
    source $HOME/.nix-profile/etc/profile.d/hm-session-vars.sh
fi

# Volta
export VOLTA_HOME=$HOME/.volta
export PATH=$PATH:$VOLTA_HOME/bin

# Node global packages
export PATH=$PATH:$HOME/.npm-global/bin

# PNPM
export PNPM_HOME="/home/aleksandar/.local/share/pnpm"
export PATH="$PNPM_HOME:$PATH"

# Docker
# export DOCKER_BIN=$HOME/.docker-bin
# Add rootless docker to path
export PATH=/home/aleksandar/.docker-bin:$PATH
export DOCKER_HOST=unix:///run/user/1000/docker.sock

# General use case
export PATH=$PATH:$HOME/.local/bin

# Flutter if installed
export PATH=$PATH:$HOME/.local/share/flutter-git/bin
export PATH="$PATH":"$HOME/.pub-cache/bin"
