#!/bin/sh

# Add all paths that will be needed. It does not matter if 
# for examlpe composer is not installed. It will be ready for 
# installation

# Add composer global packages 
# https://getcomposer.org/doc/03-cli.md#composer-home
export PATH="$PATH:$HOME/.config/composer/vendor/bin:$HOME/.composer/vendor/bin"


# Deno path
export DENO_INSTALL="$HOME/.deno"
export PATH="$DENO_INSTALL/bin:$PATH"

# Flutter does not have predefined path, so I choose ~/.flutter
export PATH="$PATH:$HOME/.flutter/flutter/bin"

# Dart global packages
export PATH="$PATH":"$HOME/.pub-cache/bin"

# Yarn global modules path, must be after node
# export PATH="$PATH:`yarn global bin`"

# Used for pip
export PATH="$PATH:$HOME/.local/bin"
export PATH="$PATH:$HOME/.fnm"
export PATH="$PATH:/usr/share/code/bin"
