#!/bin/bash

# Open neovim
alias v='nvim'

# Exit terminal
alias e='exit'

# Clear screen
alias c='clear'

# Show hidden files
alias la='ls -a'

# Copy recursively by default
alias cp='cp -R'

# Go to home folder and clear screen
alias cdc='cd ~ && clear'

# Docker Compose
alias dcm='docker-compose'
alias dcu='docker-compose up'
alias dcd='docker-compose down'

# npm
alias nrd='npm run dev'

# Kill program
alias kl='killall -9'

# apt
alias sa='sudo apt'
alias ai='sudo apt install'
alias au='sudo apt update'
alias auu='sudo apt update && sudo apt upgrade -y && sudo apt autoremove'
alias update='auu && flatpak update -y'
alias u='update'

# Check weather in terminal for current IP
alias wt='curl wttr.in'

# Attach to tmux session
alias ta='tmux attach -t'

# Rerun previous command with sudo
alias again='sudo $(fc -ln -1)'

# Git aliases
alias ga='git add'
alias gaa='git add --all'
alias gac='git add --all && git commit'
alias gc='git commit'
alias gd='git diff'
alias gp='git push'
# gs is already used in Ubuntu for ghostscript
alias gst='git status'

# Alias to go up the path
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'
alias ......='cd ../../../../..'
alias .......='cd ../../../../../..'
alias ........='cd ../../../../../../..'
alias .........='cd ../../../../../../../..'
alias ..........='cd ../../../../../../../../..'

# Enter Downloads folder
alias dw='cd ~/Downloads'

# Copy file to clipboard
alias cb='xclip -sel c < '

# Open file with proper app
alias open='xdg-open'

# Install/Update starship prompt with proper location
# --yes is to not ask for confirmation,
# and --bin-dir is location, so we don't need root to install
alias install_starship='sh -c "$(curl -fsSL https://starship.rs/install.sh)" -- --yes --bin-dir $HOME/.local/bin'

# Update Zim and it's plugins
alias update_zim='zimfw upgrade && zimfw update'

#  Update Zim and Starship
update_shell()
{
    zimfw upgrade && zimfw update
	install_starship
}

# Install flutter with all dependecies for Linux desktop development
install_flutter()
{
    git clone https://github.com/flutter/flutter.git -b stable --depth 1 ~/.local/share/flutter-sdk
    sudo apt install clang cmake ninja-build pkg-config libgtk-3-dev
    flutter precache
    flutter config --enable-linux-desktop
}

