- hosts: localhost
  # Since when testing, flatpak and vscode fails in ubuntu
  ignore_errors: yes
  pre_tasks:
    - name: Update apt
      become: true
      apt:
        update_cache: true
        upgrade: dist
  tasks:
    - include: tasks/disable_root.yml
    - include: tasks/apt.yml
    - include: tasks/zsh.yml
    - include: tasks/dotfiles.yml
    - include: tasks/node.yml
    - include: tasks/gui.yml
    - include: tasks/gaming.yml
    - include: tasks/dconf.yml
    - include: tasks/nix.yml
    - include: tasks/neovim.yml
    - include: tasks/mount.yml
      # Testing using brave as flatpak
      #- include: tasks/brave.yml
      # not needed, using home manager
      #    - include: tasks/nix_packages.yml 
