# We need to configure this before loading plugins
# This will use current dir as a title, 
# unless command is running, then it will use command name
# There are ugly spaces at the end, but it's the only way 
# to ensure that every tab has enough space  
zstyle ':zim:termtitle' hooks 'preexec' 'precmd'
zstyle ':zim:termtitle:preexec' format '${${(A)=1}}    '
zstyle ':zim:termtitle:precmd'  format '%2~           '

# Load plugin manager
source ${ZDOTDIR:-~}/.antidote/antidote.zsh
antidote load

# Enable vim mode
bindkey -v
# Disable timeout for vi mode
export KEYTIMEOUT=1

# Starship prompt
eval "$(starship init zsh)"

# zoxide navigation. jumper
eval "$(zoxide init zsh)"

# Better history search
eval "$(mcfly init zsh)"
# Use vim keys
export MCFLY_KEY_SCHEME=vim
# Do not order by rank, order by time 
export MCFLY_RESULTS_SORT=LAST_RUN

# For oh-my-zsh vi plugin. Change cursor to block when in command mode, line in insert mode
export VI_MODE_SET_CURSOR=true

# History search not working in vi mode
# bindkey '^r' history-incremental-search-backward
