# Use vim for nav
bindkey -v

# Disable timeout for vi mode
export KEYTIMEOUT=1

# Starship prompt
eval "$(starship init zsh)"

#
# Tilix fix. Run only if terminal is tilix
# https://gnunn1.github.io/tilix-web/manual/vteconfig/
# 
if [ $TILIX_ID ] || [ $VTE_VERSION ]; then
    if [ -e "/etc/profile.d/vte-2.91.sh" ]; then
        # Run this on Ubuntu/Pop
        source /etc/profile.d/vte-2.91.sh
    elif [ -e "/etc/profile.d/vte.sh" ]; then 
        # Run this on Fedora
        source /etc/profile.d/vte.sh
    fi

fi

# History search not working in vi mode
bindkey '^r' history-incremental-search-backward

# zoxide navigation
# jumper
eval "$(zoxide init zsh)"

# Better history search
export MCFLY_KEY_SCHEME=vim
eval "$(mcfly init zsh)"

# Set flutter to use brave instead of forcing me to install Chrome
# Using brave flatpak, this no longer works.
# export CHROME_EXECUTABLE="/opt/brave.com/brave/brave-browser"

